<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Remove default loop
remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_loop', 'genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.6
 */
function genesis_404() {

	?><article class="entry">

		<h1 class="entry-title">Oh no! This page is missing!</h1>
		<div class="entry-content">
			<p>The page you are looking for doesn't exist.<br>
			In the sitemap below  there is a list with all pages in this site.</p>

			<h2>Sitemap</h2>
			<ul>
				<?php wp_list_pages( 'title_li=' ); ?>
			</ul>

		</div>

		</article>';

		<?php

}

genesis();
